# Generated by Django 5.1.4 on 2024-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('course', models.CharField(choices=[('computer_science', 'Computer Science'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('ai', 'Artificial Intelligence')], max_length=20)),
                ('student_image', models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='student_image')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('marks', models.JSONField()),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
